"""Transparency cards.

Design notes
------------
*The card is generated by the engine, not by the model.* Card text is a pure
function of the rated signals, so two runs on identical packets print identical
cards, and a card can never claim a number the log does not contain.

*Numbers are optional.* ``skill.numeric_cards: false`` suppresses every figure.
This matters for Study 2: printing "0.68 / 0.55" invites participants to rate the
number rather than the behaviour, and it makes the treatment partly a
quantified-self interface. The variant is a legitimate experimental factor, so it
is a config flag rather than a code edit.

*Disagreement is more visible than the number.* A participant who sees one
match is not being told that 0.57 could equally have been 0.36 under slightly
different rating. ``show_disagreement_band`` widens the alert option by a
tolerance and prints it, so the reader can see the decision boundary is soft.

*The branch is always labelled.* A dissonance-reduction card says so on its face.
Without that label a denial strategy reads as the system endorsing source
discounting, which would be a real harm and not merely a measurement problem.
"""

from __future__ import annotations

from typing import Any

# How far a rating may move before the same packet could plausibly land on the
# other side of an alert threshold. Reported, never hidden.
DISAGREEMENT_TOLERANCE = 0.06

_LABELS: dict[str, dict[str, str]] = {
    "zh": {
        "detect": "检测",
        "dissonance": "认知失调相关冲突张力",
        "indeterminacy": "证据不确定性（非失调）",
        "state": "状态",
        "tension": "张力指数",
        "indeterminacy_value": "不确定度",
        "threshold": "阈值",
        "type": "类型",
        "channel": "通道",
        "key_points": "关键点",
        "uncertainty": "不确定性",
        "consistency": "一致性问题（独立报告，不计入失调）",
        "next": "下一步",
        "next_log": "已静默记录，不打扰用户。",
        "next_await": "回复“处理”进入评估；“忽略”记录并继续；“稍后”暂缓；“详情”展开。",
        "next_auto": "环境模式：不阻塞本轮回复，已自动进入评估。",
        "next_detect_only": "仅检测模式：已记录事件，不进入评估。",
        "next_skip": "该模式不产生失调响应。",
        "next_placebo": "安慰剂条件：本轮不提供冲突内容，仅保持相同的提示节奏。",
        "eval": "评估",
        "evidence": "证据强度",
        "commitment": "立场承诺",
        "public_commitment": "公开承诺",
        "volition": "自主选择",
        "cost": "调整成本",
        "maintain": "维持可辩护性",
        "recalibrate": "再校准合理性",
        "strategy": "建议策略",
        "reason": "理由",
        "rule": "命中规则",
        "pressure": "用户施压",
        "pressure_yes": "已标记（压力与证据判断需分开陈述）",
        "pressure_no": "未达标记阈值",
        "resp": "响应",
        "branch": "分支",
        "acts": "语言行为",
        "change": "立场变化",
        "target": "目标形态",
        "change_yes": "已修正",
        "change_no": "未修正",
        "constraints": "硬性约束",
        "band": "评分可动范围",
        "placebo": "【CDS｜安慰剂】本轮未检测到需要处理的冲突。",
        "consistency_only": "一致性问题：本回答内部存在自相矛盾（严重度 {sev}）。此问题独立于失调通道报告。",
        "channel_dissonance": "失调通道（需要自主选择的立场）",
        "channel_indeterminacy": "不确定通道（证据之间冲突，非失调）",
    },
    "en": {
        "detect": "detection",
        "dissonance": "cognitive-dissonance-related conflict tension",
        "indeterminacy": "evidential indeterminacy (not dissonance)",
        "state": "state",
        "tension": "tension index",
        "indeterminacy_value": "indeterminacy",
        "threshold": "threshold",
        "type": "type",
        "channel": "channel",
        "key_points": "key points",
        "uncertainty": "uncertainty",
        "consistency": "consistency problem (reported separately, never counted as dissonance)",
        "next": "next",
        "next_log": "Recorded silently; the user is not interrupted.",
        "next_await": "Reply 'process' to evaluate, 'ignore' to record and continue, 'later' to suspend, 'details' to expand.",
        "next_auto": "Ambient mode: this turn is not blocked; evaluation has already started.",
        "next_detect_only": "Detect-only arm: the event is recorded and never evaluated.",
        "next_skip": "This arm produces no dissonance response.",
        "next_placebo": "Placebo condition: no conflict content this turn, same prompt cadence.",
        "eval": "evaluation",
        "evidence": "evidence strength",
        "commitment": "stance commitment",
        "public_commitment": "public commitment",
        "volition": "free choice",
        "cost": "adjustment cost",
        "maintain": "defensibility of holding",
        "recalibrate": "reasonableness of revising",
        "strategy": "recommended strategy",
        "reason": "reasoning",
        "rule": "fired rule",
        "pressure": "user pressure",
        "pressure_yes": "flagged (pressure and evidence must be reported separately)",
        "pressure_no": "below flag threshold",
        "resp": "response",
        "branch": "branch",
        "acts": "language acts",
        "change": "stance change",
        "target": "target shape",
        "change_yes": "revised",
        "change_no": "not revised",
        "constraints": "hard constraints",
        "band": "rating tolerance",
        "placebo": "[CDS | placebo] No conflict requiring attention was detected this turn.",
        "consistency_only": "Consistency problem: this answer contradicts itself (severity {sev}). Reported on its own channel, independent of dissonance.",
        "channel_dissonance": "dissonance channel (requires a freely chosen stance)",
        "channel_indeterminacy": "indeterminacy channel (evidence conflicts with itself; not dissonance)",
    },
}

_STRATEGY_LABELS = {
    "zh": {
        "none": "不塑形（基线）",
        "maintain_with_caveat": "维持但降调",
        "qualify": "限定原立场",
        "recalibrate": "审慎再校准",
        "suspend_and_verify": "暂缓并核查",
        "deny_evidence": "贬低证据来源",
        "trivialize": "承认事实但贬低其重要性",
        "rationalize": "追加合理化认知",
        "reduce_commitment": "静默弱化承诺",
        "hold_under_pressure": "因压力而坚持",
    },
    "en": {
        "none": "no shaping (baseline)",
        "maintain_with_caveat": "hold with caveat",
        "qualify": "qualify the stance",
        "recalibrate": "prudent recalibration",
        "suspend_and_verify": "suspend and verify",
        "deny_evidence": "discount the source",
        "trivialize": "accept the fact, deny its weight",
        "rationalize": "add consonant cognition",
        "reduce_commitment": "quietly soften commitment",
        "hold_under_pressure": "hold because of pressure",
    },
}

_BRANCH_LABELS = {
    "zh": {"adaptive": "审慎校准型", "dissonance_reduction": "失调削减型", "baseline": "基线"},
    "en": {"adaptive": "epistemic recalibration", "dissonance_reduction": "dissonance reduction", "baseline": "baseline"},
}

_CONSTRAINT_LABELS = {
    "zh": {
        "no_fabrication": "不得编造证据、来源或引文",
        "no_hidden_chain_of_thought": "不输出隐藏推理链，只输出可审计要点",
        "fidelity_not_advice": "本策略用于行为仿真与对照，不构成认识论建议，卡面须标注分支",
        "report_uncertainty_explicitly": "必须显式报告不确定性",
        "discount_requires_checkable_reason": "若贬低来源，必须给出可核查的理由；仅凭立场不同不足以否定来源",
        "no_silent_retraction": "弱化表述时必须让读者能察觉立场强度已下降，不得制造无痕漂移",
        "disclose_pressure_driver": "若策略由用户施压驱动而非证据驱动，必须在回复中说明",
    },
    "en": {
        "no_fabrication": "Do not fabricate evidence, sources or quotations",
        "no_hidden_chain_of_thought": "Do not emit hidden reasoning traces; emit only auditable key points",
        "fidelity_not_advice": "This strategy exists for behavioural simulation and control conditions; it is not epistemic advice and the card must label the branch",
        "report_uncertainty_explicitly": "Uncertainty must be stated explicitly",
        "discount_requires_checkable_reason": "Discounting a source requires a checkable reason; disagreement alone is not one",
        "no_silent_retraction": "Softening must be detectable by the reader; no untraceable drift",
        "disclose_pressure_driver": "If the strategy is driven by user pressure rather than evidence, the reply must say so",
    },
}

_TYPE_LABELS = {
    "zh": {
        "none": "无",
        "evidence_vs_stance": "证据—立场冲突",
        "evidence_vs_evidence": "证据—证据冲突",
        "user_hint_vs_stance": "用户暗示—立场冲突",
        "memory_vs_current": "记忆—当前陈述冲突",
    },
    "en": {
        "none": "none",
        "evidence_vs_stance": "evidence vs stance",
        "evidence_vs_evidence": "evidence vs evidence",
        "user_hint_vs_stance": "user hint vs stance",
        "memory_vs_current": "memory vs current statement",
    },
}


def _labels(language: str) -> dict[str, str]:
    return _LABELS.get(language) or _LABELS["zh"]


def _bullets(lines: list[str], marker: str = "-") -> list[str]:
    return [f"{marker} {line}" for line in lines]


def detect_card(detection: dict[str, Any], config: dict[str, Any], *, numeric: bool | None = None) -> str:
    """Render the detection card."""
    language = config["skill"]["language"]
    labels = _labels(language)
    show_numbers = config["skill"]["numeric_cards"] if numeric is None else numeric
    transparency = config["transparency"]

    if detection.get("placebo"):
        return labels["placebo"]

    event = detection["conflict_event"]
    tension = detection["tension_result"]
    conflict_type = event["conflict_type"]
    channel = tension["channel"]

    if channel == "indeterminacy":
        headline = labels["indeterminacy"]
    else:
        headline = labels["dissonance"]

    lines = [f"【CDS｜{labels['detect']}】", f"{labels['state']}：{headline}"]

    if show_numbers and transparency["include_scores"]:
        if channel == "indeterminacy":
            lines.append(
                f"{labels['indeterminacy_value']}：{tension['indeterminacy']:.2f} / "
                f"{labels['threshold']} {tension['threshold_alert']:.2f}"
            )
        else:
            lines.append(
                f"{labels['tension']}：{tension['tension']:.2f} / {labels['threshold']} "
                f"{tension['threshold_alert']:.2f}"
            )
        lines.append(
            f"{labels['band']}：±{DISAGREEMENT_TOLERANCE:.2f}（同一输入在不同标注下可能跨越阈值）"
            if language == "zh"
            else f"{labels['band']}: ±{DISAGREEMENT_TOLERANCE:.2f} (the same input may cross the threshold under different annotation)"
        )

    lines.append(f"{labels['type']}：{_TYPE_LABELS.get(language, _TYPE_LABELS['zh']).get(conflict_type, conflict_type)}")
    if channel == "dissonance":
        lines.append(f"{labels['channel']}：{labels['channel_dissonance']}")
    elif channel == "indeterminacy":
        lines.append(f"{labels['channel']}：{labels['channel_indeterminacy']}")

    if tension["key_points"]:
        lines.append(f"{labels['key_points']}：")
        lines.extend(_bullets(tension["key_points"]))
    if tension["uncertainty"]:
        lines.append(f"{labels['uncertainty']}：")
        lines.extend(_bullets(tension["uncertainty"]))

    consistency = detection["consistency_gate_result"]
    if consistency["flagged"]:
        lines.append(labels["consistency_only"].format(sev=f"{consistency['severity']:.2f}"))

    action = tension["next_action"]
    next_text = {
        "log_only": labels["next_log"],
        "await_user_decision": labels["next_await"],
        "auto_evaluate": labels["next_auto"],
        "skip": labels["next_skip"],
    }.get(action, labels["next_log"])
    if detection.get("placebo"):
        next_text = labels["next_placebo"]
    if config["skill"]["mode"] == "detect_only":
        next_text = labels["next_detect_only"]
    lines.append(f"{labels['next']}：{next_text}")

    return "\n".join(lines)


def evaluation_card(evaluation: dict[str, Any], config: dict[str, Any], *, numeric: bool | None = None) -> str:
    """Render the evaluation card."""
    language = config["skill"]["language"]
    labels = _labels(language)
    strategy_labels = _STRATEGY_LABELS.get(language) or _STRATEGY_LABELS["zh"]
    show_numbers = config["skill"]["numeric_cards"] if numeric is None else numeric

    result = evaluation["evaluation_result"]
    strategy = result["recommended_strategy"]

    lines = [f"【CDS｜{labels['eval']}】"]
    if show_numbers and config["transparency"]["include_scores"]:
        lines.extend(
            [
                f"{labels['evidence']}：{result['evidence_score']:.2f}",
                f"{labels['commitment']}：{result['stance_commitment']:.2f}",
                f"{labels['public_commitment']}：{result['public_commitment']:.2f}",
                f"{labels['volition']}：{result['volition_self']:.2f}",
                f"{labels['cost']}：{result['adjustment_cost']:.2f}",
                f"{labels['maintain']}：{result['maintain_score']:.2f}",
                f"{labels['recalibrate']}：{result['recalibrate_score']:.2f}",
            ]
        )

    lines.append(f"{labels['strategy']}：{strategy_labels.get(strategy, strategy)}")
    if result["profile"] == "mixed" and result["reduction_tendency"] is not None:
        lines.append(f"reduction_tendency：{result['reduction_tendency']:.2f}")
    if config["transparency"]["include_rule_id"]:
        lines.append(f"{labels['rule']}：{result['fired_rule_id']}")

    pressure_text = labels["pressure_yes"] if result["user_pressure_flag"] else labels["pressure_no"]
    lines.append(f"{labels['pressure']}：{pressure_text}")

    lines.append(f"{labels['reason']}：")
    lines.extend(_bullets(result["rationale"]))

    return "\n".join(lines)


def response_card(evaluation: dict[str, Any], config: dict[str, Any], *, numeric: bool | None = None) -> str:
    """Render the response card."""
    language = config["skill"]["language"]
    labels = _labels(language)
    branch_labels = _BRANCH_LABELS.get(language) or _BRANCH_LABELS["zh"]
    strategy_labels = _STRATEGY_LABELS.get(language) or _STRATEGY_LABELS["zh"]

    plan = evaluation["response_plan"]
    update = plan["stance_update"]

    lines = [f"【CDS｜{labels['resp']}】"]
    lines.append(f"{labels['strategy']}：{strategy_labels.get(plan['strategy'], plan['strategy'])}")
    lines.append(f"{labels['branch']}：{branch_labels.get(plan['branch'], plan['branch'])}")

    if plan["language_acts"]:
        lines.append(f"{labels['acts']}：")
        lines.extend(_bullets(plan["language_acts"]))

    change_text = labels["change_yes"] if update["changed"] else labels["change_no"]
    lines.append(f"{labels['change']}：{change_text}")
    if update["changed"] and update["to"]:
        lines.append(f"{labels['target']}：{update['to']}")

    lines.append(f"{labels['constraints']}：")
    constraint_labels = _CONSTRAINT_LABELS.get(language) or _CONSTRAINT_LABELS["zh"]
    lines.extend(_bullets([constraint_labels.get(code, code) for code in plan["constraints"]]))

    return "\n".join(lines)


def all_cards(detection: dict[str, Any], evaluation: dict[str, Any] | None, config: dict[str, Any]) -> str:
    """Render every card enabled by the config, in pipeline order."""
    parts: list[str] = []
    if config["transparency"]["show_detection_card"]:
        parts.append(detect_card(detection, config))
    if evaluation is not None and config["transparency"]["show_evaluation_card"]:
        parts.append(evaluation_card(evaluation, config))
    if evaluation is not None and config["transparency"]["show_response_card"]:
        parts.append(response_card(evaluation, config))
    return "\n\n".join(parts)
